# Generated by Django 5.1.3 on 2024-11-19 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
